package com.example.texttosqlchat.service;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import java.util.List;
import java.util.Map;

@Service
public class DatabaseExecutionService {

    private final JdbcTemplate jdbcTemplate;

    // JdbcTemplate is automatically configured by Spring Boot if JpaRepository is used,
    // and we inject it here.
    public DatabaseExecutionService(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    /**
     * Executes the raw SQL query generated by the LLM against the SQLite database.
     * @param sqlQuery The raw SQL string (e.g., "SELECT * FROM book WHERE author='...';").
     * @return A list of maps representing the rows and columns returned by the query.
     */
    public List<Map<String, Object>> executeQuery(String sqlQuery) {
        if (sqlQuery == null || sqlQuery.isEmpty()) {
            throw new IllegalArgumentException("SQL query cannot be empty or null.");
        }

        // Basic check to prevent destructive operations
        String lowerCaseQuery = sqlQuery.toLowerCase().trim();
        if (lowerCaseQuery.startsWith("insert") || lowerCaseQuery.startsWith("update") || lowerCaseQuery.startsWith("delete") || lowerCaseQuery.startsWith("drop")) {
            throw new UnsupportedOperationException("Only SELECT queries are allowed for execution.");
        }

        System.out.println("Executing LIVE SQL: " + sqlQuery);

        // jdbcTemplate.queryForList handles execution and mapping of results
        return jdbcTemplate.queryForList(sqlQuery);
    }
}

