package com.example.texttosqlchat.dto;

import lombok.Builder;
import lombok.Data;

@Data
@Builder
public class SqlResponse {

    // The final SQL statement generated by the LLM
    private String generatedSql;

    // The result of executing the SQL (optional, for demonstration purposes)
    private Object queryResult;

    // Status message for the operation
    private String status;

}
